apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: sriov-niantic-ipam10-30-vlan9
plugin: sriov
args: '[
       {
                "if0": "enp4s0f0",
                "if0name": "sriov",
                "vlan": 9,
                "ipam": {
                        "type": "host-local",
                        "subnet": "192.168.1.0/24",
                        "rangeStart": "192.168.1.10",
                        "rangeEnd": "192.168.1.30",
                        "routes": [
                                { "dst": "0.0.0.0/0" }
                        ],
                        "gateway": "192.168.1.1"
                }
        }
]'